/*
Kevin Tieu
12-04-2020
325 Fall 2020
Reports1
*/
spool Report1.txt

ttitle Left 'CUSTOMER OVERDUE FEES REPORT' skip 2

set feedback off
set linesize 500


set long 10000000
SET wrap off



Prompt THIS REPORT IS USED TO GENENERATE ALL OUR CUSTOMERS THAT HAVE NOT PAID THEIR OVERDUE CHARGES YET.
Prompt THIS CAN BE ANYTHING FROM NOT PAYING FOR THEIR RENTAL INSTRUMENT, MUSIC LESSONS, AND/OR INSTRUMENT REPAIRS.
Prompt THE LIST HERE PROVIDES ALL CUSTOMERS WHO HAVE NOT PAID THEIR FULL NAME, CUSTOMER ID, HOME ADRESS,
Prompt HOME PHONE NUMBER, AND EMAIL. IT LETS THE BUSINESS BE ABLE TO INFORM CUSTOMER ABOUT OVERDUE FEES
Prompt AND THAT NOT PAYING THEM WILL PREVENT ANY NEW TRANACTION AND UP TO/INCLUDING BLACKLISTING.
Prompt
Prompt THE REPORT HAS BEEN MADE EASIER FOR YOUR READING SO THAT YOU CAN BE SURE TO KNOW WHERE YOU STOPPED AT
Prompt WHEN IT COMES TO CONTACTING OUR LOYAL CUSTOMERS.

Prompt

SET PAGESIZE 20
SET PAUSE ON
SET PAUSE "Press ENTER to continue reading overdue charges . . . "

COLUMN Payee FORMAT A20;
COLUMN "Customer ID" FORMAT 9990;
COLUMN Paid FORMAT A4;
COLUMN Address FORMAT A65;
COLUMN Phone FORMAT A14;
COLUMN Email FORMAT A30;

SELECT PaymentType.PaymentName as Payee, PaymentType.PaymentID as "Customer ID", PaymentType.PaymentPaid as Paid, 
       Customer.CustomerAddress as Address, Customer.CustomerPhone as Phone, Customer.CustomerEmail as Email
FROM PaymentType
FULL OUTER JOIN Customer
ON PaymentType.PaymentID = Customer.CustomerID
Where PaymentPaid = 'No'
Order by PaymentID;

spool off;